stages:
  - lint
  - test
  - build-image

include:
  - component: $CI_SERVER_HOST/buildtools/gitlab-tools/lint-dockerfile@main
  - component: $CI_SERVER_HOST/buildtools/gitlab-tools/build-oci-image@main
    inputs:
      version-cmd: jq .version -r package.json

test:
  stage: test
  image: node:20.11.1-bookworm-slim
  script:
    - npm ci --quiet >/dev/null
    - npm run -s lint
    - npm run -s test
    - npm run -s build

build-oci-image:base:
  variables:
    OCI_BUILD_PLATFORM_AMD64: linux/amd64
    OCI_BUILD_PLATFORM_ARM64v8: linux/arm64/v8
    OCI_BUILD_CACHE: 'false'
  rules:
    - if: $IMAGE_BUILD == "true"
