stages:
  - lint
  - test

include:
  - component: $CI_SERVER_HOST/buildtools/gitlab-tools/lint-dockerfile@main

test:
  stage: test
  image: node:20.11.1-bookworm-slim
  script:
    - npm ci --quiet >/dev/null
    - npm run -s lint
    - npm run -s test
    - npm run -s build
